### ISSUE TITLE
Add plugin to portal

### ISSUE THREAD

**Issue by mokraemer** [netbeanslab/nb-sort-line-tools#10]
I like this plugin, but since netbeans was moved to apache, the plugin is not available through the "official" catalog. It would be great if this can be added:
[Plugin-Portal](https://plugins.netbeans.apache.org)

It is hard to believe such a feature is not integrated in that editor.

**Comment by junichi11** [comment]
It's available in PP now: https://plugins.netbeans.apache.org/catalogue/?id=86
