### ISSUE TITLE
Needs unpack200

### ISSUE THREAD

**Issue by morvael** [netbeanslab/nb-sort-line-tools#12]
Plugin doesn't install when NB is run on JDK 14+:

```
The validation of downloaded plugins cannot be completed, cause: NBM .../update/download/org-netbeans-modules-linetools.nbm needs unpack200 to process following entries: 
netbeans/modules/docs/org-netbeans-modules-linetools.jar.pack.gz
netbeans/modules/org-netbeans-modules-linetools.jar.pack.gz
```

I think it should be repackaged.

**Comment by terax6669** [comment]
unpack for Windows
[unpack200.zip](https://github.com/netbeanslab/nb-sort-line-tools/files/9504667/unpack200.zip)

**Comment by markiewb** [comment]
@junichi11: You can rebuild the nbm **without** pack200 to make it compatible. "Set use.pack200=false in module’s project.properties if you want to completely disable using pack200 compression for the module." taken from  https://netbeans.apache.org/wiki/DevFaqNBMPack200.asciidoc

@all: Please use JDK8 or JDK11 as a workaround in the meantime. More details at https://issues.apache.org/jira/browse/NETBEANS-2842

**Comment by junichi11** [comment]
Done: https://github.com/netbeanslab/nb-sort-line-tools/releases/tag/1.24
