### ISSUE TITLE
The plug-in loading check cannot be completed. Reason: NBM

### ISSUE THREAD

**Issue by korenevskiy** [netbeanslab/nb-sort-line-tools#14]
The plug-in loading check cannot be completed. Reason: NBM
C:\Users\koren\AppData\Roaming\NetBeans\14\update\download\org-netbeans-modules-linetools.nbm needs unpack200 to process following entries: 
netbeans/modules/docs/org-netbeans-modules-linetools.jar.pack.gz
netbeans/modules/org-netbeans-modules-linetools.jar.pack.gz

**Comment by markiewb** [comment]
Duplicate of #12
