### ISSUE TITLE
org-netbeans-modules-linetools.nbm needs unpack200

### ISSUE THREAD

**Issue by sarelvdm** [netbeanslab/nb-sort-line-tools#8]
Hi,

Im using Netbeans IDE 12.2 and trying to install this plugin,
Can you please update it, so it will install on 12.2

Getting this error.

org-netbeans-modules-linetools.nbm needs unpack200 to process following entries: 
netbeans/modules/docs/org-netbeans-modules-linetools.jar.pack.gz
netbeans/modules/org-netbeans-modules-linetools.jar.pack.gz

**Comment by junichi11** [comment]
Please try to use Java 8 or Java 11.

**Comment by sarelvdm** [comment]
Thanks will do...
